version: '3.3'
services:
  joomla:
    image: joomla:latest
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - "/opt/wp-content:/var/www/html/wp-content"
    environment:
      JOOMLA_DB_HOST: joomladb:3306
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla

  joomladb:
    image: mariadb:latest
    restart: always
    volumes:
      - "/opt/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: wordpress
